USB_VID = 0x239A
USB_PID = 0x8019
USB_PRODUCT = "Mouse"
USB_MANUFACTURER = "Mouse INC"

CHIP_VARIANT = RP2040
CHIP_FAMILY = rp2

EXTERNAL_FLASH_DEVICES = "W25Q16JVxQ"

CIRCUITPY__EVE = 1
CIRCUITPY_PICODVI = 1
