name: Build UF2 for Pico

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential python3 python3-pip cmake git gcc-arm-none-eabi libnewlib-arm-none-eabi
        pip3 install adafruit-nrfutil

    - name: Init submodules
      run: git submodule update --init --recursive

    - name: Build firmware
      run: |
        make -C ports/raspberrypi BOARD=raspberry_pi_pico -j4

    - name: Upload UF2
      uses: actions/upload-artifact@v3
      with:
        name: firmware-uf2
        path: ports/raspberrypi/build-raspberry_pi_pico/firmware.uf2
